### PR TITLE
Ideas to clean up folder structure for your new module.  

### PR DESCRIPTION
**Pull request by ivan7707**
Adding bond_lab folder which will be the actual module.
moved files accordingly.  added .idea folder to gitignore file.

### CODE REVIEW

**Comment by ivan7707** [comment]
I added a test script first.py to test a simple function for the folder structure.

**Comment by glennmschultz** [comment]
Hi Ivan,

Thanks will take a look tonight when I get home.  If you don't mind I may have some question re what you have done and why.  Thanks again.

Glenn

On Oct 13, 2015, at 11:10 AM, Ivan <notifications@github.com> wrote:

I added a test script first.py to test a simple function for the folder structure.

**Comment by ivan7707** [comment]
Hi Glenn,


By all means.


I'll help as much as I can.


Ivan


________________________________

**Comment by glennmschultz** [comment]
Hi Ivan,

I see what I did wrong the bond_lab folder is the equivalent of having the R folder in the directory in which one is building the package  (in R a description file names the library directory) I read that set-up in the set up instruction but then doubted what I reading (myself).  If I run pip install -e . This will install an editable version into the python libraries, correct?  

I have two recent python books but they focus mostly on the language and very little on creating a deployment.  Do you know of any good resources outlining the development of  a python deployment. Things like documentation, namespaces etc.

Thanks,
Glenn

On Oct 13, 2015, at 11:33 AM, Ivan <notifications@github.com> wrote:

Hi Glenn,


By all means.


I'll help as much as I can.


Ivan


________________________________

**Comment by ivan7707** [comment]
Hi Glenn,

I am unclear on what you want to do with that -e flag.  What do you mean by 'python libraries'?  Are you trying to install a local version of your github repository?  

At this point in your project (at the start), what I assume you are trying to do is to setup the appropriate folder structure, and start adding the good stuff in there (the actual code) rather than putting the project on pypi, because you don't have any code to push there yet.  

There are more authoritative sources that me to help you with packaging.

Good one from EuroPython 2014:
https://www.youtube.com/watch?v=GeYis4ZuluY 

From PyPA (Python packaging authority).  
https://github.com/pypa/python-packaging-user-guide/blob/master/source/distributing.rst 


There are tonnes of videos on packaging here:

http://pyvideo.org/ 
search for packaging.  

You can email me at the email address associated with my github account too (rather than use this issues thread) to discuss.  I'll help as much as I can to get you going.   

Ivan

**Pull request merged**
